Add issues:write permission to broken links GHA
The issue reporting step of the Markdown broken link check GitHub Action
is failing due to missing permissions.

> Error: Resource not accessible by integration

There's currently a broken link (twitter-together), but the automation
isn't able to raise an issue to let us know. For now, keep the broken
link but fix the permissions. If next run is able to report an issue,
we'll know the permissions are sorted out and can fix the link.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>